# This is a Spectral ruleset file.
# Save this content as ".spectral.yaml" in the root of your project.
# To run it: spectral lint your-openapi-spec.yaml

extends:
  - spectral:oas # Extends the built-in Spectral rules for OpenAPI

rules:
  #
  # --- Custom Info Block Rules ---
  # These rules enforce your team's specific requirements for the info block.
  #

  info-description-required:
    description: "Info block must have a description."
    message: "The info block is missing a non-empty description."
    given: $.info
    then:
      field: description
      function: truthy
    severity: error

  info-contact-required:
    description: "Info object must have a contact object."
    message: "The info block must include a 'contact' object."
    given: $.info
    then:
      field: contact
      function: defined
    severity: error

  info-contact-name-required:
    description: "Contact object must have a name."
    message: "The info.contact object must include a 'name'."
    given: $.info.contact
    then:
      field: name
      function: truthy # Checks for defined and not-empty
    severity: error

  info-contact-email-format:
    description: "Contact email must be a valid email address."
    message: "The info.contact.email must be a valid email address."
    given: $.info.contact.email
    then:
      function: pattern
      functionOptions:
        match: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
    severity: error

  info-x-allowed-consumers-required:
    description: "Info block must specify x-allowed-consumers."
    message: "info.x-allowed-consumers is required and must be a comma-separated string."
    given: $.info
    then:
      field: x-allowed-consumers
      function: truthy
    severity: error

  info-x-require-approval-boolean:
    description: "Info block's x-require-approval must be a boolean."
    message: "info.x-require-approval must be a boolean (true or false)."
    given: $.info['x-require-approval']
    then:
      function: schema
      functionOptions:
        schema:
          type: boolean
    severity: error

  info-x-allowed-env-format:
    description: "Info's x-allowed-env must be a comma-separated list of dev, qa, stg, prd."
    message: "x-allowed-env must be a comma-separated list containing only 'dev', 'qa', 'stg', 'prd' (case-insensitive)."
    given: $.info['x-allowed-env']
    then:
      function: pattern
      functionOptions:
        # This regex matches a comma-separated list of the allowed values, case-insensitive.
        match: "(?i)^(dev|qa|stg|prd)(,\\s*(dev|qa|stg|prd))*$"
    severity: error

  #
  # --- Custom Common Error Schema Rule ---
  # This rule validates all 4XX and 5XX responses against your defined error schema.
  #

  common-error-schema:
    description: "All 4XX and 5XX responses must conform to the common error schema."
    message: "{{path}} does not match the common error schema. {{error}}"
    severity: error
    # 'given' targets the schema of any 4xx/5xx response that has an application/json content type.
    given: "$.paths[*][*].responses[?(@property.match(/^/) || @property === '4XX' || @property === '5XX')].content.*.schema"
    then:
      function: schema
      # The 'schema' functionOption contains the JSON Schema to validate against.
      # Note: I have corrected your 'items' definition from an array to an object,
      # which is the standard way to define an "array of objects".
      functionOptions:
        schema:
          $schema: "http://json-schema.org/draft-04/schema#"
          type: "object"
          properties:
            name:
              type: "string"
            message:
              type: "string"
            errorCode:
              type: "string"
            correlationId:
              type: "string"
            traceId:
              type: "string"
            issues:
              type: "array"
              items: # Corrected: 'items' should be an object, not an array containing an object
                type: "object"
                properties:
                  field:
                    type: "string"
                  issue:
                    type: "string"
                required:
                  - "field"
                  - "issue"
          required:
            - "name"
            - "message"
            - "errorCode"
            - "correlationId"
            - "traceId"
            - "issues"

  #
  # --- Tag Rules ---
  #
  tag-description:
    description: Please provide a description for each tag.
    message: "Each tag must have a non-empty description."
    given: $.tags[*]
    then:
      field: description
      function: truthy
    severity: error
