# This is a Spectral ruleset file.
# It extends the built-in OpenAPI rules and adds your team's custom requirements.

extends: spectral:oas # Extends the built-in Spectral rules for OpenAPI

# The 'aliases' block was removed because it created a structural inconsistency
# (a 'given' array) that conflicts with the other rules ('given' string).

rules:
  #
  # --- Custom Info Block Rules ---
  # These rules enforce your team's specific requirements for the info block.
  #

  info-description-required:
    description: "Info block must have a description."
    message: "The info block is missing a non-empty description."
    given: $.info
    then:
      field: description
      function: truthy
    severity: error

  info-contact-required:
    description: "Info object must have a contact object."
    message: "The info block must include a 'contact' object."
    given: $.info
    then:
      field: contact
      function: defined
    severity: error

  info-contact-name-required:
    description: "Contact object must have a name."
    message: "The info.contact object must include a 'name'."
    given: $.info.contact
    then:
      field: name
      function: truthy # Checks for defined and not-empty
    severity: error

  info-contact-email-required:
    description: "Contact object must have an email."
    message: "The info.contact object must include a non-empty 'email'."
    given: $.info.contact
    then:
      field: email
      function: truthy
    severity: error

  info-contact-email-format:
    description: "Contact email must be a valid email address."
    message: "The info.contact.email must be a valid email address."
    given: $.info.contact.email
    then:
      function: pattern
      functionOptions:
        match: "^.+@ual\\.com$"
        #match: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
    severity: error

  info-x-allowed-consumers-required:
    description: "Info block must specify x-allowed-consumers."
    message: "info.x-allowed-consumers is required and must be a comma-separated string."
    given: $.info
    then:
      field: "x-allowed-consumers"
      function: truthy
    severity: error

  info-x-allowed-consumers-format:
    description: "x-allowed-consumers must be a comma-separated list of values (e.g., 'consumer-a,consumer-b')."
    message: "x-allowed-consumers must be a comma-separated list (no spaces around commas). Format: 'val1,val2,val3'"
    given: "$.info['x-allowed-consumers']"
    then:
      function: pattern
      functionOptions:
        match: "^([a-zA-Z0-9_-]+)(,[a-zA-Z0-9_-]+)*$"
    severity: error

  info-x-require-approval-boolean:
    description: "Info block's x-require-approval must be a boolean."
    message: "info.x-require-approval must be a boolean (true or false)."
    given: "$.info['x-require-approval']"
    then:
      function: schema
      functionOptions:
        schema:
          type: boolean
    severity: error

  info-x-allowed-env-format:
    description: "Info's x-allowed-env must be a comma-separated list of dev, qa, stg, prd."
    message: "x-allowed-env must be a comma-separated list containing only 'dev', 'qa', 'stg', 'prd' (case-insensitive)."
    given: "$.info['x-allowed-env']"
    then:
      function: pattern
      functionOptions:
        # This regex matches a comma-separated list of the allowed values, case-insensitive.
        # We write it out manually [dD][eE][vV]... because the (?i) flag is not supported.
        match: "^([dD][eE][vV]|[qQ][aA]|[sS][tT][gG]|[pP][rR][dD])(,\\s*([dD][eE][vV]|[qQ][aA]|[sS][tT][gG]|[pP][rR][dD]))*$"
    severity: error

  #
  # --- Custom Common Error Schema Rules (Split into two rules) ---
  #
  # This rule validates all 4XX and 5XX responses defined directly in 'paths'.
  #
  common-error-schema-paths:
    description: "All 4XX/5XX responses in 'paths' must conform to the common error schema."
    message: "{{path}} does not match the common error schema. {{error}}"
    severity: error
    given: "$.paths.*.*.responses[?(@property.match(/^[45]/))].content.*.schema"
    then:
      function: schema
      functionOptions:
        schema:
          $schema: "http://json-schema.org/draft-04/schema#"
          type: "object"
          properties:
            name:
              type: "string"
            message:
              type: "string"
            errorCode:
              type: "string"
            correlationId:
              type: "string"
            traceId:
              type: "string"
            issues:
              type: "array"
              items:
                type: "object"
                properties:
                  field:
                    type: "string"
                  issue:
                    type: "string"
                required:
                  - "field"
                  - "issue"
          required:
            - "name"
            - "message"
            - "errorCode"
            - "correlationId"
            - "traceId"
            - "issues"

  #
  # This rule validates all 4XX and 5XX responses defined in 'components'.
  #
  common-error-schema-components:
    description: "All 4XX/5XX responses in 'components' must conform to the common error schema."
    message: "{{path}} does not match the common error schema. {{error}}"
    severity: error
    given: "$.components.responses[?(@property.match(/^[45]/))].content.*.schema"
    then:
      function: schema
      functionOptions:
        schema:
          $schema: "http://json-schema.org/draft-04/schema#"
          type: "object"
          properties:
            name:
              type: "string"
            message:
              type: "string"
            errorCode:
              type: "string"
            correlationId:
              type: "string"
            traceId:
              type: "string"
            issues:
              type: "array"
              items:
                type: "object"
                properties:
                  field:
                    type: "string"
                  issue:
                    type: "string"
                required:
                  - "field"
                  - "issue"
          required:
            - "name"
            - "message"
            - "errorCode"
            - "correlationId"
            - "traceId"
            - "issues"

  #
  # --- Tag Rules ---
  #
  tag-description:
    description: Please provide a description for each tag.
    message: "Each tag must have a non-empty description."
    given: $.tags[*]
    then:
      field: description
      function: truthy
    severity: error