# This file extends the default OpenAPI ruleset and adds custom rules.
# It enforces a specific info block structure and a common error schema.
extends: spectral:oas

aliases:
  ErrorResponses:
    description: "All 4XX and 5XX responses."
    targets:
      # This path is much simpler and more stable to avoid Nimma crashes.
      # It selects any response where the key (the status code)
      # starts with a '4' or a '5' using a regex match.
      - given: "$.paths.*.*.responses[?(@property.match(/^[45]/))]"
      - given: "$.components.responses[?(@property.match(/^[45]/))]"

rules:
  # Rule to enforce a common error schema for all 4XX and 5XX responses.
  common-error-schema:
    description: "All 4XX and 5XX responses must use the common error schema."
    message: "The schema for this error response does not match the common error schema. {{error}}"
    # Use the alias to target all 4XX/5XX responses
    given: $.ErrorResponses.content.*.schema
    then:
      function: schema
      functionOptions:
        schema:
          type: object
          properties:
            name:
              type: string
            message:
              type: string
            errorCode:
              type: string
            correlationId:
              type: string
            traceId:
              type: string
            issues:
              type: array
              items:
                type: object
                properties:
                  field:
                    type: string
                  issue:
                    type: string
                required:
                  - field
                  - issue
          required:
            - name
            - message
            - errorCode
            - correlationId
            - traceId
            - issues
    severity: error

  # --- Info Block Rules ---

  info-contact-required:
    description: "Info block must have a contact."
    message: "The info block is missing a contact object."
    given: $.info
    then:
      field: contact
      function: truthy
    severity: error

  info-description-required:
    description: "Info block must have a description."
    message: "The info block is missing a non-empty description."
    given: $.info
    then:
      field: description
      function: truthy
    severity: error

  info-contact-name:
    description: "Info contact must have a name."
    message: "The info.contact object is missing a 'name'."
    given: $.info.contact
    then:
      field: name
      function: truthy
    severity: error

  info-contact-email:
    description: "Info contact must have an email."
    message: "The info.contact object is missing an 'email'."
    given: $.info.contact
    then:
      field: email
      function: truthy
    severity: error

  info-x-allowed-consumers-required:
    description: "info.x-allowed-consumers is required and must be a comma separated string."
    message: "info.x-allowed-consumers is required and must be a non-empty string."
    given: $.info
    then:
      field: x-allowed-consumers
      function: truthy
    severity: error

  info-x-allowed-consumers-format:
    description: "x-allowed-consumers must be a comma-separated list of values (e.g., 'consumer-a, consumer-b')."
    message: "x-allowed-consumers must be a comma-separated list (no spaces around commas). Format: 'val1,val2,val3'"
    given: "$.info.x-allowed-consumers"
    then:
      function: pattern
      functionOptions:
        # This regex ensures it's a list of non-empty values separated by commas, with no trailing comma.
        match: "^([a-zA-Z0-9_-]+)(,[a-zA-Z0-9_-]+)*$"
    severity: "error"

  info-x-require-approval-format:
    description: "x-require-approval must be a boolean (true or false)."
    message: "info.x-require-approval must be a boolean value (true/false)."
    given: "$.info.x-require-approval"
    then:
      function: schema
      functionOptions:
        schema:
          type: boolean
    severity: "error"

  info-x-allowed-env-format:
    description: "x-allowed-env must be a comma-separated list of allowed environments (dev, qa, stg, prd)."
    message: "x-allowed-env must be a comma-separated list containing only 'dev', 'qa', 'stg', 'prd' (case-insensitive)."
    given: "$.info.x-allowed-env"
    then:
      function: pattern
      functionOptions:
        # (?i) makes it case-insensitive.
        # Allows 'dev', 'qa', 'stg', 'prd' in any combination, separated by commas.
        match: "^(?i)(dev|qa|stg|prd)(,(dev|qa|stg|prd))*$"
    severity: "error"

  # --- Tags Rules ---

  tag-description:
    description: "Please provide a description for each tag."
    message: "The tag '{{value.name}}' is missing a description."
    given: $.tags[*]
    then:
      field: description
      function: truthy
    severity: error
